# Generated by Django 5.0.7 on 2024-08-02 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pool',
        ),
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questionpool',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='QuestionPoolAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.questionpool')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'unique_together': {('question', 'pool')},
            },
        ),
        migrations.AddField(
            model_name='question',
            name='pools',
            field=models.ManyToManyField(through='questions.QuestionPoolAssociation', to='questions.questionpool'),
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_versions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='questions.question')),
            ],
            options={
                'unique_together': {('question', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.questionversion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for', to='questions.questionversion'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'question_version', 'text')},
        ),
    ]
